spring.application.name=playstation-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/pstracker
spring.datasource.username=admin
spring.datasource.password=password

# Tells Hibernate to update database schema automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false