spring.application.name=playstation-tracker
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pstracker}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.config.import=optional:file:.env

# Tells Hibernate to update database schema automatically
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Telegram
telegram.bot.username=PsPriceTrackerBot
telegram.bot.token=${TELEGRAM_BOT_TOKEN}

# Caching
spring.cache.type=caffeine
spring.cache.cache-names=searchResults
spring.cache.caffeine.spec=maximumSize=200,expireAfterWrite=10m